name: DNF-Repo For GitHub
description: 'Create a dnf-compatible repository from GitHub release'
inputs:
  # Descriptions for these input variables can be found in `README.adoc`
  from_repository:
    required: true
    type: string
  from_version:
    required: true
    type: string
  to_repository:
    required: true
    type: string
  to_branch:
    default: 'gh-pages'
    type: string
  to_path_component:
    default: 'component'
    type: string
  to_path_central:
    default: 'central'
    type: string
  max_retries:
    default: 5
    type: string
  token:
    required: true
    type: string
runs:
  using: composite
  steps:
    - name: Deploy component repo
      run: |
        gh workflow run deploy-component-repo.yaml \
        --repo "${ACTION_REPOSITORY}" \
        --ref "${ACTION_REF}" \
        --raw-field "from_repository=${{ inputs.from_repository }}" \
        --raw-field "from_version=${{ inputs.from_version }}" \
        --raw-field "to_repository=${{ inputs.to_repository }}" \
        --raw-field "to_branch=${{ inputs.to_branch }}" \
        --raw-field "to_path_component=${{ inputs.to_path_component }}" \
        --raw-field "token=${{ inputs.token }}";
        printf "DEPLOY_RUNID=%q\n" "$(gh run list --workflow=deploy-component-repo.yaml --repo "${ACTION_REPOSITORY}" --branch "${ACTION_REF}" --limit 1 --json databaseId --jq '.[0].databaseId')" >> $GITHUB_ENV
      env:
        GH_TOKEN: ${{ inputs.token }}
        ACTION_REPOSITORY: ${{ github.action_repository }}
        ACTION_REF: ${{ github.action_ref }}
      shell: bash
    - name: Retry deploy component repo until finished
      run: |
        export retries=0;
        while ! gh run watch "${{ env.DEPLOY_RUNID }}" --repo "${ACTION_REPOSITORY}" --exit-status && [[ "${retries}" -lt "${{ inputs.max_retries }}" ]]; do \
        echo "Retry ${retries}/${{ inputs.max_retries }}"; \
        gh run rerun "${{ env.DEPLOY_RUNID }}" --repo "${ACTION_REPOSITORY}"; \
        export retries="$((retries+1))"; \
        done;
        if [[ "${retries}" == "${{ inputs.max_retries }} " ]]; do echo "Max retries encountered, failing"; exit 1; fi;
      env:
        GH_TOKEN: ${{ inputs.token }}
        ACTION_REPOSITORY: ${{ github.action_repository }}
      shell: bash
    - name: Update central repo
      run: |
        gh workflow run update-central-repo.yaml \
        --repo "${ACTION_REPOSITORY}" \
        --ref "${ACTION_REF}" \
        --raw-field "to_repository=${{ inputs.to_repository }}" \
        --raw-field "to_branch=${{ inputs.to_branch }}" \
        --raw-field "to_path_component=${{ inputs.to_path_component }}" \
        --raw-field "to_path_central=${{ inputs.to_path_central }}" \
        --raw-field "token=${{ inputs.token }}";
        printf "UPDATE_RUNID=%q\n" "$(gh run list --workflow=update-central-repo.yaml --repo "${ACTION_REPOSITORY}" --branch "${ACTION_REF}" --limit 1 --json databaseId --jq '.[0].databaseId')" >> $GITHUB_ENV
      env:
        GH_TOKEN: ${{ inputs.token }}
        ACTION_REPOSITORY: ${{ github.action_repository }}
        ACTION_REF: ${{ github.action_ref }}
      shell: bash
    - name: Retry update central repo
      run: |
        export retries=0;
        while ! gh run watch "${{ env.UPDATE_RUNID }}" --repo "${ACTION_REPOSITORY}" --exit-status && [[ "${retries}" -lt "${{ inputs.max_retries }}" ]]; do \
        echo "Retry ${retries}/${{ inputs.max_retries }}"; \
        gh run rerun "${{ env.UPDATE_RUNID }}" --repo "${ACTION_REPOSITORY}"; \
        export retries="$((retries+1))"; \
        done;
        if [[ "${retries}" == "${{ inputs.max_retries }} " ]]; do echo "Max retries encountered, failing"; exit 1; fi;
      env:
        GH_TOKEN: ${{ inputs.token }}
      shell: bash
