name: DNF-Repo For GitHub
description: 'Create a dnf-compatible repository from GitHub release'
inputs:
  # Descriptions for these input variables can be found in `README.adoc`
  from_repository:
    required: true
    type: string
  from_version:
    required: true
    type: string
  to_repository:
    required: true
    type: string
  to_branch:
    default: 'gh-pages'
    type: string
  to_path_component:
    default: 'component'
    type: string
  to_path_central:
    default: 'central'
    type: string
runs:
  using: composite
  steps:
    - name: Deploy component repo
      run: |
        gh workflow run deploy-component-repo.yaml \
        --repo "${{ github.repository }}" \
        --raw-field "from_repository=${{ inputs.from_repository }}" \
        --raw-field "from_version=${{ inputs.from_version }}" \
        --raw-field "to_repository=${{ inputs.to_repository }}" \
        --raw-field "to_branch=${{ inputs.to_branch }}" \
        --raw-field "to_path_component=${{ inputs.to_path_component }}";
        printf "DEPLOY_RUNID=%q\n" "$(gh run list --workflow=deploy-component-repo.yaml --limit 1 --json databaseId --jq '.[0].databaseId')" >> $GITHUB_ENV
      shell: bash
    - name: Retry deploy component repo until finished
      run: while ! gh run watch "${{ env.DEPLOY_RUNID }}" --exit-status; do gh run rerun "${{ env.DEPLOY_RUNID }}"; done;
      shell: bash
    - name: Update central repo
      run: |
        gh workflow run update-central-repo.yaml \
        --repo "${{ github.repository }}" \
        --raw-field "from_repository=${{ inputs.from_repository }}" \
        --raw-field "from_version=${{ inputs.from_version }}" \
        --raw-field "to_repository=${{ inputs.to_repository }}" \
        --raw-field "to_branch=${{ inputs.to_branch }}" \
        --raw-field "to_path_component=${{ inputs.to_path_component }}" \
        --raw-field "to_path_central=${{ inputs.to_path_central }}";
        ; printf UPDATE_RUNID=%q\n" "$(gh run list --workflow=update-central-repo.yaml --limit 1 --json databaseId --jq '.[0].databaseId')" >> $GITHUB_ENV
      shell: bash
    - name: Retry update central repo
      run: while ! gh run watch "${{ env.UPDATE_RUNID }}" --exit-status; do gh run rerun "${{ env.UPDATE_RUNID }}"; done;
      shell: bash
