= DFG_01 (DNF-Repo For GitHub)

A simple to use GitHub Action that creates and updates `dnf` compatible repository configuration and commits them to a specific branch.

== Features

- Creates and commits per-version repository configuration files from any GitHub release that contains `.rpm` files. This allows user to use a specific per-version `.repo` definition to install exactly the wanted version without having to specify it during install process.

- Combines, commits and updates a special `releases` repository configuration files that is made from all of the other per-version repositories. This allows user to use a single `.repo` definition to upgrade and downgrade versions as wanted.

== Limitations

Pushing to only the current repository is supported.

== Usage

The workflow needs to have `contents: write` https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#permissions[permissions].

.Required permissions
[source,yaml]
----
permissions:
  contents: write
----

Add a `uses: teragrep/dfg_01@main` https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#jobsjob_idstepsuses[step] to your workflow.

.Minimal configuration
[source,yaml]
----
- name: Create repo
  uses: teragrep/dfg_01@main
  with:
    repository: teragrep/example-repository
    version: 1.0.0
----

.Full configuration
[source,yaml]
----
- name: Create repo
  uses: teragrep/dfg_01@main
  with:
    repository: teragrep/example-repository
    version: 1.0.0
    to_branch: custom-branch
    to_path: custom/path
----

== Documentation

These are arguments to be used in `with:` block.

|===
|Input argument|Description|Required|Default

|`repository`
|The used GitHub repository in `user/repository` format
|Yes
|

|`version`
|The exact release version.
|Yes
|

|`to_branch`
|The branch where repository files are commited to
|No
|`gh-pages`

|`to_path`
|The path where repository files are commited to. No trailing slash required.
|No
|`repo`
